/****************************************************************************
**
** Metadata for AcroPDFLib generated by dumpcpp v5.12.11 using
** dumpcpp.exe -o acropdf {CA8A9780-280D-11CF-A24D-444553540000}
** from the type library C:\Program Files (x86)\Common Files\Adobe\Acrobat\ActiveX\AcroPDF.dll
**
****************************************************************************/

#define QAX_DUMPCPP_ACROPDFLIB_NOINLINES
#include "acropdf.h"

using namespace AcroPDFLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[122];
    char stringdata0[1500];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 19, 0),
QT_MOC_LITERAL(1, 20, 17, 0),
QT_MOC_LITERAL(2, 38, 15, 0),
QT_MOC_LITERAL(3, 54, 11, 0),
QT_MOC_LITERAL(4, 66, 8, 0),
QT_MOC_LITERAL(5, 75, 11, 0),
QT_MOC_LITERAL(6, 87, 14, 0),
QT_MOC_LITERAL(7, 102, 11, 0),
QT_MOC_LITERAL(8, 114, 16, 0),
QT_MOC_LITERAL(9, 131, 11, 0),
QT_MOC_LITERAL(10, 143, 21, 0),
QT_MOC_LITERAL(11, 165, 9, 0),
QT_MOC_LITERAL(12, 175, 0, 0),
QT_MOC_LITERAL(13, 176, 4, 0),
QT_MOC_LITERAL(14, 181, 6, 0),
QT_MOC_LITERAL(15, 188, 4, 0),
QT_MOC_LITERAL(16, 193, 4, 0),
QT_MOC_LITERAL(17, 198, 15, 0),
QT_MOC_LITERAL(18, 214, 4, 0),
QT_MOC_LITERAL(19, 219, 6, 0),
QT_MOC_LITERAL(20, 226, 4, 0),
QT_MOC_LITERAL(21, 231, 4, 0),
QT_MOC_LITERAL(22, 236, 15, 0),
QT_MOC_LITERAL(23, 252, 20, 0),
QT_MOC_LITERAL(24, 273, 11, 0),
QT_MOC_LITERAL(25, 285, 14, 0),
QT_MOC_LITERAL(26, 300, 13, 0),
QT_MOC_LITERAL(27, 314, 22, 0),
QT_MOC_LITERAL(28, 337, 23, 0),
QT_MOC_LITERAL(29, 361, 18, 0),
QT_MOC_LITERAL(30, 380, 9, 0),
QT_MOC_LITERAL(31, 390, 17, 0),
QT_MOC_LITERAL(32, 408, 20, 0),
QT_MOC_LITERAL(33, 429, 23, 0),
QT_MOC_LITERAL(34, 453, 18, 0),
QT_MOC_LITERAL(35, 472, 10, 0),
QT_MOC_LITERAL(36, 483, 5, 0),
QT_MOC_LITERAL(37, 489, 20, 0),
QT_MOC_LITERAL(38, 510, 12, 0),
QT_MOC_LITERAL(39, 523, 13, 0),
QT_MOC_LITERAL(40, 537, 13, 0),
QT_MOC_LITERAL(41, 551, 13, 0),
QT_MOC_LITERAL(42, 565, 11, 0),
QT_MOC_LITERAL(43, 577, 8, 0),
QT_MOC_LITERAL(44, 586, 8, 0),
QT_MOC_LITERAL(45, 595, 11, 0),
QT_MOC_LITERAL(46, 607, 14, 0),
QT_MOC_LITERAL(47, 622, 11, 0),
QT_MOC_LITERAL(48, 634, 12, 0),
QT_MOC_LITERAL(49, 647, 7, 0),
QT_MOC_LITERAL(50, 655, 9, 0),
QT_MOC_LITERAL(51, 665, 5, 0),
QT_MOC_LITERAL(52, 671, 18, 0),
QT_MOC_LITERAL(53, 690, 12, 0),
QT_MOC_LITERAL(54, 703, 13, 0),
QT_MOC_LITERAL(55, 717, 13, 0),
QT_MOC_LITERAL(56, 731, 8, 0),
QT_MOC_LITERAL(57, 740, 11, 0),
QT_MOC_LITERAL(58, 752, 7, 0),
QT_MOC_LITERAL(59, 760, 9, 0),
QT_MOC_LITERAL(60, 770, 3, 0),
QT_MOC_LITERAL(61, 774, 5, 0),
QT_MOC_LITERAL(62, 780, 3, 0),
QT_MOC_LITERAL(63, 784, 6, 0),
QT_MOC_LITERAL(64, 791, 11, 0),
QT_MOC_LITERAL(65, 803, 8, 0),
QT_MOC_LITERAL(66, 812, 15, 0),
QT_MOC_LITERAL(67, 828, 14, 0),
QT_MOC_LITERAL(68, 843, 13, 0),
QT_MOC_LITERAL(69, 857, 12, 0),
QT_MOC_LITERAL(70, 870, 12, 0),
QT_MOC_LITERAL(71, 883, 16, 0),
QT_MOC_LITERAL(72, 900, 11, 0),
QT_MOC_LITERAL(73, 912, 8, 0),
QT_MOC_LITERAL(74, 921, 11, 0),
QT_MOC_LITERAL(75, 933, 11, 0),
QT_MOC_LITERAL(76, 945, 10, 0),
QT_MOC_LITERAL(77, 956, 4, 0),
QT_MOC_LITERAL(78, 961, 2, 0),
QT_MOC_LITERAL(79, 964, 13, 0),
QT_MOC_LITERAL(80, 978, 15, 0),
QT_MOC_LITERAL(81, 994, 19, 0),
QT_MOC_LITERAL(82, 1014, 1, 0),
QT_MOC_LITERAL(83, 1016, 1, 0),
QT_MOC_LITERAL(84, 1018, 1, 0),
QT_MOC_LITERAL(85, 1020, 1, 0),
QT_MOC_LITERAL(86, 1022, 20, 0),
QT_MOC_LITERAL(87, 1043, 14, 0),
QT_MOC_LITERAL(88, 1058, 1, 0),
QT_MOC_LITERAL(89, 1060, 13, 0),
QT_MOC_LITERAL(90, 1074, 10, 0),
QT_MOC_LITERAL(91, 1085, 17, 0),
QT_MOC_LITERAL(92, 1103, 14, 0),
QT_MOC_LITERAL(93, 1118, 12, 0),
QT_MOC_LITERAL(94, 1131, 9, 0),
QT_MOC_LITERAL(95, 1141, 11, 0),
QT_MOC_LITERAL(96, 1153, 8, 0),
QT_MOC_LITERAL(97, 1162, 17, 0),
QT_MOC_LITERAL(98, 1180, 2, 0),
QT_MOC_LITERAL(99, 1183, 14, 0),
QT_MOC_LITERAL(100, 1198, 6, 0),
QT_MOC_LITERAL(101, 1205, 3, 0),
QT_MOC_LITERAL(102, 1209, 7, 0),
QT_MOC_LITERAL(103, 1217, 8, 0),
QT_MOC_LITERAL(104, 1226, 11, 0),
QT_MOC_LITERAL(105, 1238, 4, 0),
QT_MOC_LITERAL(106, 1243, 3, 0),
QT_MOC_LITERAL(107, 1247, 5, 0),
QT_MOC_LITERAL(108, 1253, 6, 0),
QT_MOC_LITERAL(109, 1260, 13, 0),
QT_MOC_LITERAL(110, 1274, 6, 0),
QT_MOC_LITERAL(111, 1281, 7, 0),
QT_MOC_LITERAL(112, 1289, 7, 0),
QT_MOC_LITERAL(113, 1297, 13, 0),
QT_MOC_LITERAL(114, 1311, 20, 0),
QT_MOC_LITERAL(115, 1332, 7, 0),
QT_MOC_LITERAL(116, 1340, 26, 0),
QT_MOC_LITERAL(117, 1367, 28, 0),
QT_MOC_LITERAL(118, 1396, 36, 0),
QT_MOC_LITERAL(119, 1433, 20, 0),
QT_MOC_LITERAL(120, 1454, 11, 0),
QT_MOC_LITERAL(121, 1466, 32, 0)
    },
    "AcroPDFLib::AcroPDF\0Event Interface 1\0_IAcroPDFEvents\0Interface 0\0IAcroPDF\0"
    "Interface 2\0IAcroAXDocShim\0Interface 3\0ISPOpenDocuments\0Interface 4\0"
    "_IAcroAXDocShimEvents\0exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0"
    "signal\0argc\0argv\0CheckinDocument\0bstrDocumentLocation\0CheckinType\0CheckinComment\0"
    "bKeepCheckout\0CheckoutDocumentPrompt\0bstrDocumentLocationRaw\0fEditAfterCheckout\0"
    "varProgID\0CreateNewDocument\0bstrTemplateLocation\0bstrDefaultSaveLocation\0"
    "CreateNewDocument2\0IDispatch*\0pDisp\0DiscardLocalCheckout\0EditDocument\0"
    "EditDocument2\0EditDocument3\0fUseLocalCopy\0GetVersions\0LoadFile\0fileName\0"
    "NewBlogPost\0bstrProviderId\0bstrBlogUrl\0bstrBlogName\0OnError\0OnMessage\0Print\0"
    "PromptedOnLastOpen\0ViewDocument\0ViewDocument2\0ViewDocument3\0OpenType\0ViewInExcel\0"
    "SiteUrl\0SessionId\0Cmd\0Sheet\0Row\0Column\0execCommand\0strArray\0goBackwardStack\0"
    "goForwardStack\0gotoFirstPage\0gotoLastPage\0gotoNextPage\0gotoPreviousPage\0"
    "postMessage\0printAll\0printAllFit\0shrinkToFit\0printPages\0from\0to\0printPagesFit\0"
    "printWithDialog\0setCurrentHighlight\0a\0b\0c\0d\0setCurrentHightlight\0setCurrentPage\0"
    "n\0setLayoutMode\0layoutMode\0setMessageHandler\0messageHandler\0setNamedDest\0"
    "namedDest\0setPageMode\0pageMode\0setShowScrollbars\0On\0setShowToolbar\0setSrc\0"
    "src\0setView\0viewMode\0setViewRect\0left\0top\0width\0height\0setViewScroll\0offset\0"
    "setZoom\0percent\0setZoomScroll\0AcroPDFLib::IAcroPDF\0control\0AcroPDFLib::IAcroAXDocShim\0"
    "AcroPDFLib::ISPOpenDocuments\0AcroPDFLib::AdobeSPOpenDocumentsShim\0"
    "ISPOpenDocumentsShim\0Interface 1\0AcroPDFLib::ISPOpenDocumentsShim\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_AcroPDFLib__AcroPDF[] = {

 // content:
    7, // revision
    0,  // classname
    5, 14, // classinfo
    59, 24, // methods
    2, 598, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 
    5, 6, 
    7, 8, 
    9, 10, 

// signal: name, argc, parameters, tag, flags
    11, 4, 319, 12, 5,
    17, 1, 328, 12, 5,
    19, 3, 331, 12, 5,

// slot: name, argc, parameters, tag, flags
    22, 3, 338, 12, 11,
    22, 4, 345, 12, 9,
    27, 2, 354, 12, 11,
    27, 3, 359, 12, 9,
    31, 2, 366, 12, 9,
    34, 3, 371, 12, 9,
    37, 1, 378, 12, 9,
    38, 1, 381, 12, 11,
    38, 2, 384, 12, 9,
    39, 2, 389, 12, 11,
    39, 3, 394, 12, 9,
    40, 3, 401, 12, 11,
    40, 4, 408, 12, 9,
    42, 0, 417, 12, 9,
    43, 1, 418, 12, 9,
    45, 3, 421, 12, 9,
    49, 0, 428, 12, 9,
    50, 0, 429, 12, 9,
    51, 0, 430, 12, 9,
    52, 0, 431, 12, 9,
    53, 1, 432, 12, 11,
    53, 2, 435, 12, 9,
    54, 2, 440, 12, 11,
    54, 3, 445, 12, 9,
    55, 3, 452, 12, 11,
    55, 4, 459, 12, 9,
    57, 7, 468, 12, 11,
    57, 8, 483, 12, 9,
    64, 1, 500, 12, 9,
    66, 0, 503, 12, 9,
    67, 0, 504, 12, 9,
    68, 0, 505, 12, 9,
    69, 0, 506, 12, 9,
    70, 0, 507, 12, 9,
    71, 0, 508, 12, 9,
    72, 1, 509, 12, 9,
    73, 0, 512, 12, 9,
    74, 1, 513, 12, 9,
    76, 2, 516, 12, 9,
    79, 3, 521, 12, 9,
    80, 0, 528, 12, 9,
    81, 4, 529, 12, 9,
    86, 4, 538, 12, 9,
    87, 1, 547, 12, 9,
    89, 1, 550, 12, 9,
    91, 1, 553, 12, 9,
    93, 1, 556, 12, 9,
    95, 1, 559, 12, 9,
    97, 1, 562, 12, 9,
    99, 1, 565, 12, 9,
    100, 1, 568, 12, 9,
    102, 1, 571, 12, 9,
    104, 4, 574, 12, 9,
    109, 2, 583, 12, 9,
    111, 1, 588, 12, 9,
    113, 3, 591, 12, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Bool, QMetaType::QString, QMetaType::Int, QMetaType::QString, 23, 24, 25,
    QMetaType::Bool, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::Bool, 23, 24, 25, 26,
    QMetaType::Bool, QMetaType::QString, QMetaType::Bool, 28, 29,
    QMetaType::Bool, QMetaType::QString, QMetaType::Bool, QMetaType::QVariant, 28, 29, 30,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, 32, 33,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::QString, 36, 32, 33,
    QMetaType::Bool, QMetaType::QString, 28,
    QMetaType::Bool, QMetaType::QString, 23,
    QMetaType::Bool, QMetaType::QString, QMetaType::QVariant, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, 36, 23,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::QVariant, 36, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Bool, 36, 23, 41,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Bool, QMetaType::QVariant, 36, 23, 41, 30,
    QMetaType::QVariant,
    QMetaType::Bool, QMetaType::QString, 44,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, 46, 47, 48,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Bool,
    QMetaType::Bool, QMetaType::QString, 23,
    QMetaType::Bool, QMetaType::QString, QMetaType::QVariant, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, 36, 23,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::QVariant, 36, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Int, 36, 23, 56,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Int, QMetaType::QVariant, 36, 23, 56, 30,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 58, 44, 59, 60, 61, 62, 63,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::QVariant, 58, 44, 59, 60, 61, 62, 63, 30,
    QMetaType::Void, QMetaType::QVariant, 65,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QVariant, 65,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 75,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 77, 78,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Bool, 77, 78, 75,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 82, 83, 84, 85,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 82, 83, 84, 85,
    QMetaType::Void, QMetaType::Int, 88,
    QMetaType::Void, QMetaType::QString, 90,
    QMetaType::Void, QMetaType::QVariant, 92,
    QMetaType::Void, QMetaType::QString, 94,
    QMetaType::Void, QMetaType::QString, 96,
    QMetaType::Void, QMetaType::Bool, 98,
    QMetaType::Void, QMetaType::Bool, 98,
    QMetaType::Void, QMetaType::QString, 101,
    QMetaType::Void, QMetaType::QString, 103,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 105, 106, 107, 108,
    QMetaType::Void, QMetaType::QString, QMetaType::Double, 103, 110,
    QMetaType::Void, QMetaType::Double, 112,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, 112, 105, 106,

 // properties: name, type, flags
    92, QMetaType::QVariant, 0x29015003, 		 // QVariant messageHandler
    101, QMetaType::QString, 0x0a015003, 		 // QString src

    0 // eod
};

const QMetaObject AcroPDF::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AcroPDFLib__AcroPDF, 0, 0, 0 }
};

void *AcroPDF::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AcroPDFLib::AcroPDF"))
        return static_cast<void*>(const_cast<AcroPDF*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_AcroPDFLib__IAcroPDF[] = {

 // content:
    7, // revision
    114,  // classname
    0, 0, // classinfo
    3, 14, // methods
    1, 48, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    11, 4, 29, 12, 5,
    17, 1, 38, 12, 5,
    19, 3, 41, 12, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

 // properties: name, type, flags
    115, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IAcroPDF::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AcroPDFLib__IAcroPDF, 0, 0, 0 }
};

void *IAcroPDF::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AcroPDFLib::IAcroPDF"))
        return static_cast<void*>(const_cast<IAcroPDF*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AcroPDFLib__IAcroAXDocShim[] = {

 // content:
    7, // revision
    116,  // classname
    0, 0, // classinfo
    34, 14, // methods
    3, 306, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    11, 4, 184, 12, 5,
    17, 1, 193, 12, 5,
    19, 3, 196, 12, 5,

// slot: name, argc, parameters, tag, flags
    42, 0, 203, 12, 9,
    43, 1, 204, 12, 9,
    51, 0, 207, 12, 9,
    64, 1, 208, 12, 9,
    66, 0, 211, 12, 9,
    67, 0, 212, 12, 9,
    68, 0, 213, 12, 9,
    69, 0, 214, 12, 9,
    70, 0, 215, 12, 9,
    71, 0, 216, 12, 9,
    72, 1, 217, 12, 9,
    73, 0, 220, 12, 9,
    74, 1, 221, 12, 9,
    76, 2, 224, 12, 9,
    79, 3, 229, 12, 9,
    80, 0, 236, 12, 9,
    81, 4, 237, 12, 9,
    86, 4, 246, 12, 9,
    87, 1, 255, 12, 9,
    89, 1, 258, 12, 9,
    91, 1, 261, 12, 9,
    93, 1, 264, 12, 9,
    95, 1, 267, 12, 9,
    97, 1, 270, 12, 9,
    99, 1, 273, 12, 9,
    100, 1, 276, 12, 9,
    102, 1, 279, 12, 9,
    104, 4, 282, 12, 9,
    109, 2, 291, 12, 9,
    111, 1, 296, 12, 9,
    113, 3, 299, 12, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::QVariant,
    QMetaType::Bool, QMetaType::QString, 44,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QVariant, 65,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QVariant, 65,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 75,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 77, 78,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Bool, 77, 78, 75,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 82, 83, 84, 85,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 82, 83, 84, 85,
    QMetaType::Void, QMetaType::Int, 88,
    QMetaType::Void, QMetaType::QString, 90,
    QMetaType::Void, QMetaType::QVariant, 92,
    QMetaType::Void, QMetaType::QString, 94,
    QMetaType::Void, QMetaType::QString, 96,
    QMetaType::Void, QMetaType::Bool, 98,
    QMetaType::Void, QMetaType::Bool, 98,
    QMetaType::Void, QMetaType::QString, 101,
    QMetaType::Void, QMetaType::QString, 103,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 105, 106, 107, 108,
    QMetaType::Void, QMetaType::QString, QMetaType::Double, 103, 110,
    QMetaType::Void, QMetaType::Double, 112,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, 112, 105, 106,

 // properties: name, type, flags
    115, QMetaType::QString, 0x0a055003, 		 // QString control
    92, QMetaType::QVariant, 0x29015003, 		 // QVariant messageHandler
    101, QMetaType::QString, 0x0a015003, 		 // QString src

    0 // eod
};

const QMetaObject IAcroAXDocShim::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AcroPDFLib__IAcroAXDocShim, 0, 0, 0 }
};

void *IAcroAXDocShim::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AcroPDFLib::IAcroAXDocShim"))
        return static_cast<void*>(const_cast<IAcroAXDocShim*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AcroPDFLib__ISPOpenDocuments[] = {

 // content:
    7, // revision
    117,  // classname
    0, 0, // classinfo
    26, 14, // methods
    1, 318, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    11, 4, 144, 12, 5,
    17, 1, 153, 12, 5,
    19, 3, 156, 12, 5,

// slot: name, argc, parameters, tag, flags
    22, 3, 163, 12, 11,
    22, 4, 170, 12, 9,
    27, 2, 179, 12, 11,
    27, 3, 184, 12, 9,
    31, 2, 191, 12, 9,
    34, 3, 196, 12, 9,
    37, 1, 203, 12, 9,
    38, 1, 206, 12, 11,
    38, 2, 209, 12, 9,
    39, 2, 214, 12, 11,
    39, 3, 219, 12, 9,
    40, 3, 226, 12, 11,
    40, 4, 233, 12, 9,
    45, 3, 242, 12, 9,
    52, 0, 249, 12, 9,
    53, 1, 250, 12, 11,
    53, 2, 253, 12, 9,
    54, 2, 258, 12, 11,
    54, 3, 263, 12, 9,
    55, 3, 270, 12, 11,
    55, 4, 277, 12, 9,
    57, 7, 286, 12, 11,
    57, 8, 301, 12, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Bool, QMetaType::QString, QMetaType::Int, QMetaType::QString, 23, 24, 25,
    QMetaType::Bool, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::Bool, 23, 24, 25, 26,
    QMetaType::Bool, QMetaType::QString, QMetaType::Bool, 28, 29,
    QMetaType::Bool, QMetaType::QString, QMetaType::Bool, QMetaType::QVariant, 28, 29, 30,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, 32, 33,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::QString, 36, 32, 33,
    QMetaType::Bool, QMetaType::QString, 28,
    QMetaType::Bool, QMetaType::QString, 23,
    QMetaType::Bool, QMetaType::QString, QMetaType::QVariant, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, 36, 23,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::QVariant, 36, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Bool, 36, 23, 41,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Bool, QMetaType::QVariant, 36, 23, 41, 30,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, 46, 47, 48,
    QMetaType::Bool,
    QMetaType::Bool, QMetaType::QString, 23,
    QMetaType::Bool, QMetaType::QString, QMetaType::QVariant, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, 36, 23,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::QVariant, 36, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Int, 36, 23, 56,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Int, QMetaType::QVariant, 36, 23, 56, 30,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 58, 44, 59, 60, 61, 62, 63,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::QVariant, 58, 44, 59, 60, 61, 62, 63, 30,

 // properties: name, type, flags
    115, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject ISPOpenDocuments::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AcroPDFLib__ISPOpenDocuments, 0, 0, 0 }
};

void *ISPOpenDocuments::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AcroPDFLib::ISPOpenDocuments"))
        return static_cast<void*>(const_cast<ISPOpenDocuments*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AcroPDFLib__AdobeSPOpenDocumentsShim[] = {

 // content:
    7, // revision
    118,  // classname
    2, 14, // classinfo
    26, 18, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    3, 119, 
    120, 8, 

// signal: name, argc, parameters, tag, flags
    11, 4, 148, 12, 5,
    17, 1, 157, 12, 5,
    19, 3, 160, 12, 5,

// slot: name, argc, parameters, tag, flags
    22, 3, 167, 12, 11,
    22, 4, 174, 12, 9,
    27, 2, 183, 12, 11,
    27, 3, 188, 12, 9,
    31, 2, 195, 12, 9,
    34, 3, 200, 12, 9,
    37, 1, 207, 12, 9,
    38, 1, 210, 12, 11,
    38, 2, 213, 12, 9,
    39, 2, 218, 12, 11,
    39, 3, 223, 12, 9,
    40, 3, 230, 12, 11,
    40, 4, 237, 12, 9,
    45, 3, 246, 12, 9,
    52, 0, 253, 12, 9,
    53, 1, 254, 12, 11,
    53, 2, 257, 12, 9,
    54, 2, 262, 12, 11,
    54, 3, 267, 12, 9,
    55, 3, 274, 12, 11,
    55, 4, 281, 12, 9,
    57, 7, 290, 12, 11,
    57, 8, 305, 12, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Bool, QMetaType::QString, QMetaType::Int, QMetaType::QString, 23, 24, 25,
    QMetaType::Bool, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::Bool, 23, 24, 25, 26,
    QMetaType::Bool, QMetaType::QString, QMetaType::Bool, 28, 29,
    QMetaType::Bool, QMetaType::QString, QMetaType::Bool, QMetaType::QVariant, 28, 29, 30,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, 32, 33,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::QString, 36, 32, 33,
    QMetaType::Bool, QMetaType::QString, 28,
    QMetaType::Bool, QMetaType::QString, 23,
    QMetaType::Bool, QMetaType::QString, QMetaType::QVariant, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, 36, 23,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::QVariant, 36, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Bool, 36, 23, 41,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Bool, QMetaType::QVariant, 36, 23, 41, 30,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, 46, 47, 48,
    QMetaType::Bool,
    QMetaType::Bool, QMetaType::QString, 23,
    QMetaType::Bool, QMetaType::QString, QMetaType::QVariant, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, 36, 23,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::QVariant, 36, 23, 30,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Int, 36, 23, 56,
    QMetaType::Bool, 0x80000000 | 35, QMetaType::QString, QMetaType::Int, QMetaType::QVariant, 36, 23, 56, 30,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, 58, 44, 59, 60, 61, 62, 63,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::QVariant, 58, 44, 59, 60, 61, 62, 63, 30,

    0 // eod
};

const QMetaObject AdobeSPOpenDocumentsShim::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AcroPDFLib__AdobeSPOpenDocumentsShim, 0, 0, 0 }
};

void *AdobeSPOpenDocumentsShim::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AcroPDFLib::AdobeSPOpenDocumentsShim"))
        return static_cast<void*>(const_cast<AdobeSPOpenDocumentsShim*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_AcroPDFLib__ISPOpenDocumentsShim[] = {

 // content:
    7, // revision
    121,  // classname
    0, 0, // classinfo
    3, 14, // methods
    1, 48, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    11, 4, 29, 12, 5,
    17, 1, 38, 12, 5,
    19, 3, 41, 12, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

 // properties: name, type, flags
    115, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject ISPOpenDocumentsShim::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AcroPDFLib__ISPOpenDocumentsShim, 0, 0, 0 }
};

void *ISPOpenDocumentsShim::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AcroPDFLib::ISPOpenDocumentsShim"))
        return static_cast<void*>(const_cast<ISPOpenDocumentsShim*>(this));
    return QAxObject::qt_metacast(_clname);
}

